---
author: "Will Godwin"
output:
  epuRate::epurate:
    toc: FALSE
    number_sections: FALSE
    code_folding: "hide"
---
<br>

## University of California, San Francisco (2019)
**Godwin, W.**, …, Oldenburg C.E. (2020-in press). Trachoma Prevalence Following Discontinuation of Mass Azithromycin Distribution. Journal of Infectious Disease.

Thomas M. Lietman, …, **Godwin, W.**, NTD Modelling Consortium discussion group on trachoma (2019). Insights from mathematical modelling and quantitative analysis on the proposed 2030 goals for trachoma. Journal of Infectious Disease.

<br>

## University of Washington (2016-2018)

My Masters thesis investigated the interactive effects of air pollution and ambient temperature on mortality in Mexico City using generalized additive models. Full text provided [here](https://pdfs.semanticscholar.org/6ed7/ce24142555d65037fd539910344b902a4d30.pdf).

<br>

## Institute for Health Metrics and Evaluation (2015-2018)

The below selected publications represent my contributions to the Global Burden of Disease study over 3 years.

Walker, K., …, **Godwin, W.**, Health Effects Institute & Global Burden of Disease Project Collaboration (2019). State of Global Air 2019-Special Report on Global Exposure to Air Pollution and its Disease Burden

Shupler, M., **Godwin, W.**, Frostad, J., Gustafson, P., Arku, R., Brauer, M (2018). Global estimation of exposure to fine particulate matter (PM 2.5) from household air pollution.

Gakidou, E., …, **Godwin, W. W.**, & GBD 2016 Risk Factors Collaborators (2017). Global, regional, and national comparative risk assessment of 84 behavioural, environmental and occupational, and metabolic risks or clusters of risks, 1990–2016: a systematic analysis for the Global Burden of Disease Study 2016.

Forouzanfar, M. H., …, **Godwin, W. W**., & GBD Collaborators (2016). Global, regional, and national comparative risk assessment of 79 behavioural, environmental and occupational, and metabolic risks or clusters of risks, 1990–2015: a systematic analysis for the Global Burden of Disease Study 2015.

Lim, S. S., …., **Godwin, W. W.**, & GBD 2015 SDG Collaborators (2016). Measuring the health-related Sustainable Development Goals in 188 countries: a baseline analysis from the Global Burden of Disease Study 2015.

Wang, H., …, **Godwin, W. W.**, & GBD 2015 Mortality and Causes of Death Collaborators (2016). Global, regional, and national life expectancy, all-cause mortality, and cause-specific mortality for 249 causes of death, 1980–2015: a systematic analysis for the Global Burden of Disease Study 2015.

<br>

## Google scholar

A full list of publications is available in [Google scholar](https://scholar.google.com/citations?user=P6mnUBsAAAAJ&hl=en).